# Copyright (c) 2025 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: STMicroelectronics
      url-base: https://github.com/STMicroelectronics

  defaults:
    remote: STMicroelectronics

  projects:
    - name: stselib
      repo-path: STSELib
      revision: 96847405f20491601e1cbbdd7ad5b7e6aacf721f
      path: 6tron/lib/stselib
