# Copyright (c) 2026 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: STMicroelectronics
      url-base: https://github.com/STMicroelectronics
    - name: Dev
      url-base: https://github.com/Grolleau-Benjamin

  defaults:
    # remote: STMicroelectronics
    remote: Dev

  projects:
    - name: stselib
      repo-path: STSELib
      revision: 5125dbe54ae9a147f560766c8edc61bff99c6369
      path: modules/lib/stselib
