# Copyright (c) 2025 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: STMicroelectronics
      url-base: https://github.com/STMicroelectronics
    - name: LocalFork
      url-base: https://github.com/Grolleau-Benjamin

  defaults:
    # remote: STMicroelectronics
    remote: LocalFork

  projects:
    - name: stselib
      repo-path: STSELib
      revision: dc93a1c41ed630c8f2178f29630c1c27d004c228
      path: modules/lib/stselib
