# Copyright (c) 2025 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: STMicroelectronics
      url-base: https://github.com/STMicroelectronics
    - name: Dev
      url-base: https://github.com/Grolleau-Benjamin

  defaults:
    # remote: STMicroelectronics
    remote: Dev

  projects:
    - name: stselib
      repo-path: STSELib
      revision: c452b45ad4541199edbb698295f40f0097332654
      path: modules/lib/stselib
